### ISSUE TITLE
Adjustable toolchain

### ISSUE THREAD

**Issue by nkaskov** [NilFoundation/zkllvm#217]
Toolchain on this stage will achieve flexibility in many ways:
- [ ] Support of flexible components for instructions (not intrinsics - for now)
- [ ] Ability to change arithmetization setting (minimum  - each type columns amounts)
- [ ] First version of components adjustment policy (place components in the table depending on some primitive cost function)
