### ISSUE TITLE
Add new memory management functions for reallocations and etc.

### ISSUE THREAD

**Issue by aleasims** [NilFoundation/zkLLVM#462]
This is an umbrella issue for expanding zkLLVM set of memory management functions to complete.

Right now we have only `malloc` and `free`. This is not enough to handle even growable vectors in both C++ and Rust. We need to support full set of memory management functions in our compilers and assigner.

Tasks:

- [ ] NilFoundation/zkllvm-circifier/issues/96
- [ ] NilFoundation/zkllvm-rslang/issues/75
- [ ] NilFoundation/zkllvm-stdlib/issues/13
- [ ] NilFoundation/zkllvm-assigner/issues/166
- [ ] Add examples which use these function (in Rust and C++)
